# Generated by Django 2.2.4 on 2019-11-18 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtreamOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('defenders', models.PositiveIntegerField(default=1)),
                ('gun', models.BooleanField(default=True)),
                ('car', models.BooleanField(default=True)),
                ('costume', models.BooleanField(default=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete')], default='active', max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('coments', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('defenders', models.PositiveIntegerField(default=1)),
                ('gun', models.BooleanField(default=True)),
                ('car', models.BooleanField(default=True)),
                ('costume', models.BooleanField(default=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete')], default='active', max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('coments', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='account.UserType')),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ListOrderPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exorder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_orders', to='order.ExtreamOrder')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_orders', to='order.Order')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_performer', to='account.UserType')),
            ],
            options={
                'ordering': ('order',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
