# Generated by Django 2.2.4 on 2019-11-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listorderprice',
            name='exorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_orders', to='order.ExtreamOrder'),
        ),
        migrations.AlterField(
            model_name='listorderprice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_orders', to='order.Order'),
        ),
    ]
