# Generated by Django 2.2.4 on 2019-11-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191118_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listorderprice',
            options={'ordering': ('-price',)},
        ),
        migrations.AlterIndexTogether(
            name='listorderprice',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='listorderprice',
            name='slug',
        ),
    ]
