# Generated by Django 2.2.4 on 2019-11-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191118_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listorderprice',
            old_name='exorder',
            new_name='extreamorder',
        ),
    ]
