# Generated by Django 2.2.4 on 2019-11-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191118_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='listorderprice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
