# Generated by Django 2.2.4 on 2019-11-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_listorderprice_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listorderprice',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
